### ISSUE TITLE
TypeScript typings?

### ISSUE THREAD

**Issue by cakoose** [charmander/strict-cookie-parser#2]
It would be nice if this module had TypeScript types.  There are three options:
1. Write the code in TypeScript.
2. Add a "index.d.ts" file with the type definitions to this repo.
3. Add type definitions via the DefinitelyTyped project.

The options are ordered according to my preference.  The earlier options are more likely to keep the types in sync with the library, which is better for users of the library.

Downside of option 1: Adds a build step for you.
Downside of option 2: Puts the types in your repo, which maybe you don't want to maintain.

Are you ok with either option 1 or 2?  If so, I can try preparing a PR.

**Comment by charmander** [comment]
Sorry for missing this. I don’t really like any of the options, but 1 might be the least bad – at least it can’t go out of sync. I’ll figure something out.

**Comment by charmander** [comment]
Published a questionably manually tested index.d.ts in 3.2.0, with future improvements planned.
