### ISSUE TITLE
This library is rejecting a Cookie header sent up by Chrome

### ISSUE THREAD

**Issue by cakoose** [charmander/strict-cookie-parser#3]
This cookie header value is sent up by Chrome and is rejected by `strict-cookie-parser`:

```
> const {parseCookieHeader} = require('strict-cookie-parser');
undefined
> parseCookieHeader('g_state={"i_l":0}');
null
```

I'm not sure if `'g_state={"i_l":0}'` is valid according to the spec, though.  It ended up in my cookies through the "Sign in with Google" button, which I'm trying to add to my site.

**Comment by cakoose** [comment]
Ok, looks like it's the double quotes that is causing the problem.  And the cookie spec appears to say that double quotes are not allowed:

```
 cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
 cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash
```

Let me make sure I'm not doing something wrong on my end...

**Comment by charmander** [comment]
It isn’t valid according to RFC 6265, no. Looks like it breaks other libraries too, including [Tornado](https://stackoverflow.com/questions/66864766/one-tap-login-g-state-cookie-is-not-parseable-on-http-cookies-simplecookie) and the .NET `CookieContainer`.

You might want to use a different cookie parser until Google fixes that (if they ever do).

**Comment by cakoose** [comment]
Will try to collect more information and file a bug with Chrome.

**Comment by charmander** [comment]
It’s a bug with whatever sets/uses the `g_state` cookie, not a bug with Chrome (unless Chrome is integrated with this and the non-Chrome flow doesn’t set the cookie in the same format). Browsers have to be compatible with all kinds of spec breaks that exist on the web.
